      *> reject-at: 2002 2014 2023
      *> kb/Work PB1274 - ISO/IEC 1989:2023 section 13.18.42.4 GR3: "If the FINAL phrase is specified, the implicit
      *> method definitions generated by the PROPERTY clause shall include the FINAL phrase in their METHOD-ID
      *> paragraphs."  Section 11.7.3 SR3: "If the OVERRIDE phrase is specified, there shall be a method with the same
      *> method resolution signature ... The method in the superclass shall not be defined with the FINAL clause."
      *>   cite.py: OK  13.18.42.4 3)  /  OK  11.7.3 3)
      *> The subclass overrides the FINAL accessor that PROPERTY IS FINAL defines.
       IDENTIFICATION DIVISION.
       CLASS-ID. PB1274FB INHERITS FROM BASE.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       REPOSITORY.
           CLASS BASE.
       IDENTIFICATION DIVISION.
       OBJECT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 N PIC 9 VALUE 1 PROPERTY IS FINAL.
       PROCEDURE DIVISION.
       END OBJECT.
       END CLASS PB1274FB.

       IDENTIFICATION DIVISION.
       CLASS-ID. PB1274FS INHERITS FROM PB1274FB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       REPOSITORY.
           CLASS PB1274FB.
       IDENTIFICATION DIVISION.
       OBJECT.
       PROCEDURE DIVISION.
       METHOD-ID. GET PROPERTY N OVERRIDE.
       DATA DIVISION.
       LINKAGE SECTION.
       01 LK PIC 9.
       PROCEDURE DIVISION RETURNING LK.
       MAIN.
           MOVE 9 TO LK.
       END METHOD.
       END OBJECT.
       END CLASS PB1274FS.
