// Copyright (c) 2026 Brent Rector. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file in the project root.
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CobolNet.Tools.ArchCensus;

/// <summary>
/// THE stated rule for "a tool wrote this file" — the census measures generated code for the population check and
/// follows its references, but never reports a generated type as a god class, a clone or a dead member, because no
/// one edits it. A document is generated when its project-relative path has an <c>obj</c> or <c>Generated</c>
/// directory segment (MSBuild's intermediates; the ANTLR parser, a build output), when its name ends in
/// <c>.g.cs</c>, <c>.g.i.cs</c> or <c>.Designer.cs</c>, or when its first comment carries <c>&lt;auto-generated</c>.
/// A source generator's output is generated by construction (<see cref="LoadedSolution"/>).
/// </summary>
internal static class GeneratedCode
{
    private static readonly string[] Directories = ["obj", "Generated"];
    private static readonly string[] Suffixes = [".g.cs", ".g.i.cs", ".Designer.cs"];

    public static bool IsGenerated(string projectRelativePath, SyntaxTree tree)
    {
        string[] segments = projectRelativePath.Split('/', '\\');
        if (segments.SkipLast(1).Any(s => Directories.Contains(s, StringComparer.OrdinalIgnoreCase)))
        {
            return true;
        }

        if (Suffixes.Any(s => projectRelativePath.EndsWith(s, StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        SyntaxTrivia first = tree.GetRoot().GetLeadingTrivia()
            .FirstOrDefault(t => t.IsKind(SyntaxKind.SingleLineCommentTrivia) || t.IsKind(SyntaxKind.MultiLineCommentTrivia));
        return first.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }
}
